# SPRD Platform Support
snd-soc-sc881x-objs	:= sc881x.o
obj-$(CONFIG_SND_SPRD_SOC_SC881X)+= snd-soc-sc881x.o
snd-soc-kylew-objs	:= kylew.o
obj-$(CONFIG_SND_SPRD_SOC_KYLEW)	+= snd-soc-kylew.o
snd-soc-sc882x-objs	:= sc882x.o
obj-$(CONFIG_SND_SPRD_SOC_SC882X)	+= snd-soc-sc882x.o
snd-soc-bt-i2s-objs	:= bt-i2s.o
obj-$(CONFIG_SND_SPRD_SOC_BT_I2S)	+= snd-soc-bt-i2s.o
obj-$(CONFIG_SND_SPEAKER_PA)	+= speaker-pa.o

obj-$(CONFIG_SND_SPRD_SOC_AUDIO_DMA)	+= dai/
obj-$(CONFIG_SND_SPRD_SOC_VBC)	+= dai/vbc/
obj-$(CONFIG_SND_SPRD_SOC_VAUDIO)	+= dai/vaudio/
obj-$(CONFIG_SND_SPRD_SOC_I2S)		+= dai/i2s/
obj-$(CONFIG_SND_SOC_DOLPHIN)		+= codec/dolphin/
obj-$(CONFIG_SND_SOC_SPRD_CODEC)	+= codec/sprd/
obj-$(CONFIG_SND_SOC_NULL_CODEC)	+= codec/null-codec/
